include:
    # Metadata shared my many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml

    # OS builds.
    - local: .gitlab/os-linux.yml
    - local: .gitlab/os-macos.yml
    - local: .gitlab/os-windows.yml

stages:
    - build
    - test

################################################################################
# Job declarations
#
# Each job must pull in each of the following keys:
#
#   - a "base image"
#   - a build script
#   - tags for the jobs
#     - already provided for upload and CI update jobs
#   - rules for when to run the job
#
# Additionally, jobs may also contain:
#
#   - artifacts
#   - dependency/needs jobs for required jobs
################################################################################

# Linux

## Spack

build:spack-centos7:
    extends:
        - .centos7
        - .spack_build_linux
        - .linux_builder_tags
        - .run_scheduled

## Linux

build:fedora33-static-mpi-offscreen-osmesa-python:
    extends:
        - .fedora33_static_mpi_offscreen_osmesa_python
        - .cmake_build_linux
        - .linux_builder_tags
        - .cmake_build_artifacts
        - .run_manually

test:fedora33-static-mpi-offscreen-osmesa-python:
    extends:
        - .fedora33_static_mpi_offscreen_osmesa_python
        - .cmake_test_linux
        - .linux_tester_tags
        - .cmake_test_artifacts
        - .run_automatically
    dependencies:
        - build:fedora33-static-mpi-offscreen-osmesa-python
    needs:
        - build:fedora33-static-mpi-offscreen-osmesa-python

build:fedora31-shared-icc-mpi-python:
    extends:
        - .fedora31_shared_icc_mpi_python
        - .cmake_build_linux
        - .linux_builder_tags
        - .cmake_build_artifacts
        - .run_manually

test:fedora31-shared-icc-mpi-python:
    extends:
        - .fedora31_shared_icc_mpi_python
        - .cmake_test_linux
        - .linux_tester_tags
        - .cmake_test_artifacts
        - .run_automatically
    dependencies:
        - build:fedora31-shared-icc-mpi-python
    needs:
        - build:fedora31-shared-icc-mpi-python

# macOS

build:macos-python-qt:
    extends:
        - .macos_python_qt
        - .cmake_build_macos
        - .macos_builder_tags
        - .cmake_build_artifacts
        - .run_manually

test:macos-python-qt:
    extends:
        - .macos_python_qt
        - .cmake_test_macos
        - .macos_builder_tags
        - .cmake_test_artifacts
        - .run_automatically
    dependencies:
        - build:macos-python-qt
    needs:
        - build:macos-python-qt

# Windows

build:windows-vs2019-kits-mpi-python-qt:
    extends:
        - .windows_vs2019_kits_mpi_python_qt
        - .cmake_build_windows
        - .windows_builder_tags
        - .cmake_build_artifacts
        - .run_manually

test:windows-vs2019-kits-mpi-python-qt:
    extends:
        - .windows_vs2019_kits_mpi_python_qt
        - .cmake_test_windows
        - .windows_builder_tags
        - .cmake_build_artifacts
        - .run_automatically
    dependencies:
        - build:windows-vs2019-kits-mpi-python-qt
    needs:
        - build:windows-vs2019-kits-mpi-python-qt
    timeout: 90 minutes
    # There are some failing tests; in the interest of getting builds working,
    # allow tests to fail (for now).
    allow_failure: true

build:windows-vs2019-qt:
    extends:
        - .windows_vs2019_qt
        - .cmake_build_windows
        - .windows_builder_tags
        - .cmake_build_artifacts
        - .run_manually

test:windows-vs2019-qt:
    extends:
        - .windows_vs2019_qt
        - .cmake_test_windows
        - .windows_builder_tags
        - .cmake_build_artifacts
        - .run_automatically
    dependencies:
        - build:windows-vs2019-qt
    needs:
        - build:windows-vs2019-qt
    # There are some failing tests; in the interest of getting builds working,
    # allow tests to fail (for now).
    allow_failure: true

# Deployment

## Documentation

build:documentation:
    extends:
        - .fedora33
        - .doxygen_build_linux
        - .linux_builder_tags
        - .doxygen_log_artifacts
        - .run_scheduled

# Triggers

## Superbuild

build:superbuild:
    extends:
        - .run_superbuild_trigger
    stage: build
    variables:
        PARAVIEW_BRANCH: $CI_COMMIT_REF_NAME
        RSYNC_UPLOAD_ENABLE: "true"
    trigger:
        project: paraview/paraview-superbuild
        branch: $CI_COMMIT_REF_NAME
        strategy: depend
